### ISSUE TITLE
Doesn't build on OS X 10.11 El Capitan - bump pleeease version to 4.0.1

### ISSUE THREAD

**Issue by cpjolly** [danielhusar/gulp-pleeease#13]
This doesn't build on OS X 10.11 because pleeease 3.x depends on node-sass 2.x, which doesn't build on OS X 10.11 .

Local testing with bumping the dependency version for pleeease to 4.0.1 fixes it, because this depends on node-sass 3.3.3, which does build on OS X 10.11.

If there are no incompatibilities with pleeease 4.x, it would be nice if the major version number of gulp-pleeease was kept at 1.x. That way, this change will be picked up by downstream dependencies, such as sc5-styleguide

**Comment by danielhusar** [comment]
Oh didn't notice that pleease is already on 4.0, will bump it. Thanks.

**Comment by cpjolly** [comment]
Yeah... Upgraded my Mac yesterday and this caught me today when I tried to re-install sc5-styleguide

**Comment by danielhusar** [comment]
I have updated pleease to `4.0.0`.
I have bumped major to `2.0.0` as you need node `4.0.0` now.
