### ISSUE TITLE
Callback is not triggered if an empty CSS file processed

### ISSUE THREAD

**Issue by KennyLindahl** [danielhusar/gulp-pleeease#15]
My code looks like this:
<pre>
gulp.src(options.tmpDir + '/*.css')
    .pipe(please({
        'autoprefixer': {
            'browsers': options.autoprefixer.supportedBrowsers,
            'cascade': true
         }
      }))
      .pipe(gulp.dest(options.tmpDir))
      .on('end', callback);
</pre>

If any of the CSS files is emtpy then the callback will not be triggered.
If i write a comment in or anything instead of an empty file it works.

Right now i will have to do a work around to solve this, but please consider fixing this.
Thanks in advance, 
/Kenny

**Comment by danielhusar** [comment]
Good catch :)

Should be fixed now in `2.0.2`

**Comment by KennyLindahl** [comment]
Wow, you're quick!
Great work, i will verify this tomorrow.

Thanks
