### ISSUE TITLE
Update pleeease dependency

### ISSUE THREAD

**Issue by joshuaadickerson** [danielhusar/gulp-pleeease#18]
I just upgraded to Node 8 and now my builds are failing because the dependency for pleeease is at 4.1.0. This causes node-sass to be at version 3.8.0. node-sass 3.8 is incompatible with Node 8, but they updated their package.json and all that needs to happen is this package needs to be updated.

**Comment by danielhusar** [comment]
Hey if you delete node modules and reinstall all dependencies pleeease `4.2.1` should be picked automatically.
